name: MERF-FSP
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-image
  - imagemagick<7.0.9
  - pyvips
  - pixman=0.36.0
  - glumpy
  - pytorch
  - torchvision
  - jupyter
  - pip
  - pip:
      - black
      - jupyter_contrib_nbextensions
