name: MERF-FSP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - scikit-image
  - pyvips
  - pyopengl
  - jupyter
  - pytorch 
  - torchvision 
  - cudatoolkit=10.1
  - pip
  - pip:
      - black
      - jupyter_contrib_nbextensions
      - glumpy  
